### ISSUE TITLE
Czarne elementy po aktualizacji w trybie ciemny

### ISSUE THREAD

**Issue by lasic-pro** [PepperTweaker/PepperTweaker#11]
Po aktualizacji peppera cześć tekstów jest domyśle czarna (i przez to nieczytelna) w trybie ciemnym

**Comment by bearbyt3z** [comment]
Poprawione. Od wersji [0.9.147](https://github.com/PepperTweaker/PepperTweaker/releases/tag/v0.9.147) powinno już wyglądać jak wcześniej (mogą być drobne różnice w kolorach czcionek).

**Comment by bearbyt3z** [comment]
Poprawione. Od wersji [0.9.147](https://github.com/PepperTweaker/PepperTweaker/releases/tag/v0.9.147) powinno już wyglądać jak wcześniej (mogą być drobne różnice w kolorach czcionek).

**Comment by lasic-pro** [comment]
Problem występuje jeszcze po najechaniu na tytuł okazji, która już wygasła.

**Comment by bearbyt3z** [comment]
> Problem występuje jeszcze po najechaniu na tytuł okazji, która już wygasła.

Poprawione w wersji 0.9.148 => [tag](https://github.com/PepperTweaker/PepperTweaker/releases/tag/v0.9.148), [commit](https://github.com/PepperTweaker/PepperTweaker/commit/8483480a3e3ec2d4a9ed53101109017d39bcf055).
