### ISSUE TITLE
Problem z kolorem czcionek

### ISSUE THREAD

**Issue by lasic-pro** [PepperTweaker/PepperTweaker#12]
Są jasne na jasnym tle dla (przynajmniej) srebrnych reniferów. 

![2024-10-27_13-27-14](https://github.com/user-attachments/assets/53f852b9-3968-46f0-973f-c96d2a4c0f30)
![image](https://github.com/user-attachments/assets/6c9ae50c-bd73-4a1c-a94c-ee8abccb02a4)

**Comment by bearbyt3z** [comment]
Nadpisałem kolory w [wersji 0.9.164](https://github.com/PepperTweaker/PepperTweaker/commit/281852f02b77aca4d6e2302cd873467f4f2a6404), tak żeby było zawsze takie samo tło, grające z ciemnym motywem.

Tak to wygląda:
![Screenshot_20241028_173853](https://github.com/user-attachments/assets/7d94dc57-17ac-4021-82df-82936560c51a)

Tych powiadomień nie da się skutecznie debugować. Wydaje mi się nawet, że w aplikacji renifery wyskakują szybciej. Na desktopie od wczoraj nie mogłem wygenerować ani jednego, dopiero dzisiaj sprawdzałem, jak to wygląda...

**Comment by lasic-pro** [comment]
Jak dla mnie spoko :).
