### ISSUE TITLE
Przejście do najlepszych komentarzy

### ISSUE THREAD

**Issue by Trin32** [PepperTweaker/PepperTweaker#2]
Cześć.

Czy można szybko przejść do "najlepszych komentarzy" w danej okazji?
W przypadku cytowanych komentarzy jest możliwość kliknięcia w datę napisania, a przy "najlepszych" nie widzę by była opcja inna niż wejście w "Permalink" i kopiowanie adresu.
Czasem warto zostawić kolejne polubienie lub przeszukać kolejne odpowiedzi, a kopiowanie linków trochę zniechęca.

Pozdrawiam.

**Comment by bearbyt3z** [comment]
Cześć,

była jeszcze niedawno taka możliwość (dokładniej Permalinki, o których piszesz, były podmieniane na zwykłe linki zamiast pojawiającego się pop upu), ale niestety Pepper jakiś czas temu zmienił całkowicie sposób ładowania komentarzy na stronach okazji w taki sposób, że są one ładowane dynamicznie już po wczytaniu całej strony (początkowo widać tylko animowane gify imitujące zamazany tekst komentarzy). Tweaker bazuje na starej wersji wczytywania komentarzy z całą stroną i dlatego funkcje związane z komentarzami przestały działać (podobnie np. przyciski "Lubię" w najlepszych komentarzach). Problem w tym, że trzeba by przerobić stary system, tak aby obserwował dynamiczne dodawanie komentarzy, a nie bazował na wczytywaniu ich razem ze stroną. Niestety wiąże się to ze sporymi zmianami (trzeba dodać odpowiednie MutationObservery, z czym jest zawsze sporo zabawy) i na razie nie za bardzo mogę na to znaleźć czas :/

**Comment by Trin32** [comment]
Ach, faktycznie. 
Nie zwróciłem na to uwagi, myślałem że przeglądarka nie nadąża za wczytywaniem strony.

Dzięki za odpowiedź. Pozdrawiam :)
