### ISSUE TITLE
Brak updatów na Greasy Fork

### ISSUE THREAD

**Issue by Igloczek** [PepperTweaker/PepperTweaker#9]
@bearbyt3z Z jakiegoś powodu na Greasy Fork ostatnia wersja to 0.9.61, czyli nie ma żadnych releasów z ostatniego miesiąca.

Nie wiem, czy to brak automatyzacji, czy się coś popsuło, więc wrzucam link do docsów, gdzie jest opisane jak to ustawić
https://greasyfork.org/en/users/webhook-info?locale_override=1

**Comment by bearbyt3z** [comment]
Celowo nie ma automatycznej synchronizacji na Greasy Fork, bo aktualizacja tam pojawia się dopiero, jak napiszę zbiorczy komentarz o ostatnich poprawkach w dyskusji poświęconej rozszerzeniu, żeby było wiadomo, co się zmieniło:
https://www.pepper.pl/dyskusji/peppertweaker-beta-testy-188008

Dodanie automatyzacji to są dwa kliki, ale obsługa feedbacku i pytań użytkowników, to zupełnie inna bajka, więc przez oficjalny kanał dystrybucji poprawki lecą partiami ;)

Jeśli ktoś poczuje potrzebę szybszej aktualizacji, to zawsze można skopiować sobie kod z GH. Każda poprawka ma swoją wersję, więc można łatwo wrócić do oficjalnego kanału dystrybucji.

**Comment by bearbyt3z** [comment]
Celowo nie ma automatycznej synchronizacji na Greasy Fork, bo aktualizacja tam pojawia się dopiero, jak napiszę zbiorczy komentarz o ostatnich poprawkach w dyskusji poświęconej rozszerzeniu, żeby było wiadomo, co się zmieniło:
https://www.pepper.pl/dyskusji/peppertweaker-beta-testy-188008

Dodanie automatyzacji to są dwa kliki, ale obsługa feedbacku i pytań użytkowników, to zupełnie inna bajka, więc przez oficjalny kanał dystrybucji poprawki lecą partiami ;)

Jeśli ktoś poczuje potrzebę szybszej aktualizacji, to zawsze można skopiować sobie kod z GH. Każda poprawka ma swoją wersję, więc można łatwo wrócić do oficjalnego kanału dystrybucji.
